version: '3'
services:
  app:
    container_name: docker-jwt-nodejs
    restart: always
    build: .
    ports:
    - '80:3000'
    links:
    - mysql
  mysql:
    container_name: mysql
    image: mysql
