version: '2'
services:
  app:
    container_name: docker-jwt-nodejs
    restart: always
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/usr/src/app
    depends_on:
    - redis
    links:
    - redis
    ports:
    - '8000:8000'
    expose:
    - "8000"
    command: "npm start"
  redis:
    image: redis
    container_name: cache

